
production:
 adapter: mysql2
 encoding: utf8
 pool: 5
 database: test
 username: root
 password: root
 socket: /var/run/mysqld/mysqld.sock

development:
 adapter: mysql2
 encoding: utf8
 pool: 5
 database: testapp_development
 username: root
 password: root
 socket: /var/run/mysqld/mysqld.sock








